"""AGENTS.md generator — produces agent-facing codebase documentation."""

from __future__ import annotations

from datetime import datetime

from vaultknox.onboard.analyzer.engine import AnalysisReport


def generate_agents_md(report: AnalysisReport) -> str:
    sections: list[str] = []
    sections.append(f"# AGENTS.md — {report.repo_name}")
    sections.append("")
    sections.append(f"*Auto-generated by VaultKnox Onboard on {datetime.now().strftime('%Y-%m-%d')}*")
    sections.append("")

    sections.append("## Project Overview")
    sections.append("")
    if report.primary_language:
        sections.append(f"**Primary language**: {report.primary_language}")
    if report.language_count > 1:
        langs = list(report.languages.keys())
        sections.append(f"**Additional languages**: {', '.join(langs[1:5])}")
    sections.append("")

    if report.frameworks:
        sections.append("## Tech Stack")
        sections.append("")
        for framework, path in report.frameworks.items():
            sections.append(f"- **{framework}** (`{path}`)")
        sections.append("")

    sections.append("## Build, Test, and Lint Commands")
    sections.append("")
    commands = _infer_commands(report)
    for cmd_name, cmd in commands.items():
        sections.append(f"- **{cmd_name}**: `{cmd}`")
    sections.append("")

    sections.append("## Project Structure")
    sections.append("")
    if report.source_dirs:
        sections.append(f"**Source directories**: `{'`, `'.join(report.source_dirs)}`")
    if report.test_dirs:
        sections.append(f"**Test directories**: `{'`, `'.join(report.test_dirs)}`")
    if report.entry_points:
        sections.append(f"**Entry points**: `{'`, `'.join(report.entry_points)}`")
    sections.append("")

    top_files = report.structure.get("top_level_files", [])
    if top_files:
        sections.append("### Top-Level Files")
        sections.append("")
        config_files_list = report.structure.get("config_files", [])
        for f in top_files:
            marker = " [CONFIG]" if f in config_files_list else ""
            sections.append(f"- `{f}`{marker}")
    sections.append("")

    if report.dependencies:
        sections.append("## Dependencies")
        sections.append("")
        for dep_type, dep_data in report.dependencies.items():
            if not dep_data.get("found"):
                continue
            sections.append(f"### {dep_type.replace('_', ' ').title()}")
            sections.append("")
            if "dependencies" in dep_data:
                deps = dep_data["dependencies"]
                if isinstance(deps, dict):
                    sections.append(f"*{len(deps)} packages*")
                elif isinstance(deps, list):
                    sections.append(f"*{len(deps)} packages*")
            if "optional_dependencies" in dep_data:
                sections.append(f"*Optional groups: {', '.join(dep_data['optional_dependencies'].keys())}*")
            sections.append("")
    sections.append("")

    sections.append("## Agent Guidelines")
    sections.append("")
    sections.append("### Code Style")
    sections.append("- Follow existing code patterns and conventions in the repository.")
    sections.append("- Match indentation, naming, and import styles of surrounding code.")
    sections.append("- Do not introduce new dependencies without explicit necessity.")
    sections.append("")
    sections.append("### Before Making Changes")
    sections.append("1. Read the relevant source files to understand existing patterns.")
    sections.append("2. Check if there are existing tests covering the area you're changing.")
    sections.append("3. Run the test suite before and after changes.")
    sections.append("")
    sections.append("### Safety Rules")
    sections.append("- Never commit secrets, API keys, or credentials.")
    sections.append("- Never delete tests to make them pass.")
    sections.append("- Never use `as any` or type suppression in TypeScript.")
    sections.append("- Always verify changes build before reporting success.")
    sections.append("")

    if report.issues:
        sections.append("## Known Issues (Detected by Analysis)")
        sections.append("")
        for issue in report.issues:
            sections.append(f"- {issue}")
        sections.append("")

    return "\n".join(sections)


def _infer_commands(report: AnalysisReport) -> dict[str, str]:
    commands: dict[str, str] = {}
    if report.has_nodejs:
        pkg = report.dependencies.get("nodejs", {})
        scripts = pkg.get("scripts", {})
        if "build" in scripts: commands["build"] = "npm run build"
        if "test" in scripts: commands["test"] = "npm run test"
        if "lint" in scripts: commands["lint"] = "npm run lint"
        if "dev" in scripts: commands["dev"] = "npm run dev"
    if report.has_python:
        commands["test"] = "python -m pytest"
        if report.frameworks.get("uv"): commands["install"] = "uv sync"
        elif report.frameworks.get("Poetry"): commands["install"] = "poetry install"
        else: commands["install"] = "pip install -e .[dev]"
    if report.has_rust:
        commands["build"] = "cargo build"
        commands["test"] = "cargo test"
        commands["lint"] = "cargo clippy"
    if report.has_go:
        commands["build"] = "go build ./..."
        commands["test"] = "go test ./..."
    if not commands:
        commands["build"] = "[detect build system]"
        commands["test"] = "[detect test framework]"
    return commands
