"""Architecture overview generator."""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

from vaultknox.onboard.analyzer.engine import AnalysisReport

_API_SKIP_DIRS = {
    "__pycache__", ".git", "node_modules", ".venv", "venv",
    "target", "dist", "build", ".next", ".nuxt",
    "tests", "test", "__tests__", "spec",
}


def generate_arch_overview(report: AnalysisReport) -> str:
    sections: list[str] = []
    sections.append(f"# {report.repo_name} — Architecture Overview")
    sections.append("")
    sections.append(f"*Auto-generated by VaultKnox Onboard on {datetime.now().strftime('%Y-%m-%d')}*")
    sections.append("")

    sections.append("## Summary")
    sections.append("")
    sections.append(f"This is a **{report.primary_language or 'multi-language'}** project "
                    f"with {report.language_count} language(s) detected.")
    if report.frameworks:
        sections.append(f"Key frameworks: {', '.join(list(report.frameworks.keys())[:8])}.")
    sections.append("")

    sections.append("## Module Layout")
    sections.append("")
    for src_dir in report.source_dirs:
        sections.append(f"### `{src_dir}/`")
        sections.append("")
        src_path = Path(report.repo_path) / src_dir
        if src_path.is_dir():
            subdirs = sorted([
                d.name for d in src_path.iterdir()
                if d.is_dir() and not d.name.startswith(".") and d.name not in _API_SKIP_DIRS
            ])
            for sd in subdirs[:15]:
                sections.append(f"- `{sd}/`")
        sections.append("")
    if not report.source_dirs:
        sections.append("No standard source directories detected (src/, lib/, app/, etc.)")
        sections.append("")

    if report.entry_points:
        sections.append("## Entry Points")
        sections.append("")
        for ep in report.entry_points[:5]:
            sections.append(f"- `{ep}`")
        sections.append("")

    sections.append("## Data Flow (Inferred)")
    sections.append("")
    if report.has_nodejs:
        if any("Express" in f for f in report.frameworks):
            sections.append("- **HTTP** to Express middleware to route handlers to response")
        elif any("Next.js" in f for f in report.frameworks):
            sections.append("- **Pages/API routes** to React components to user-facing UI")
        else:
            sections.append("- Request to handler to service to data layer")
    elif report.has_python:
        sections.append("- CLI entry to service layer to data access to external APIs")
    elif report.has_rust:
        sections.append("- Main module to service modules to external I/O")
    else:
        sections.append("- Entry point to business logic to I/O layer")
    sections.append("")

    if report.dependencies:
        sections.append("## Key Dependencies")
        sections.append("")
        for dep_type, dep_data in report.dependencies.items():
            if not dep_data.get("found"): continue
            sections.append(f"### {dep_type.replace('_', ' ').title()}")
            sections.append("")
            deps = dep_data.get("dependencies", [])
            if isinstance(deps, dict):
                for name in list(deps.keys())[:10]:
                    sections.append(f"- `{name}`")
            elif isinstance(deps, list):
                for item in deps[:10]:
                    sections.append(f"- `{item}`")
            sections.append("")

    sections.append("## Testing Strategy")
    sections.append("")
    if report.test_dirs:
        sections.append(f"Test directories: `{'`, `'.join(report.test_dirs)}`")
    else:
        sections.append("No test directory detected. Consider adding tests.")
    sections.append("")

    return "\n".join(sections)
