"""Documenter engine — orchestrates AGENTS.md, README.md, SETUP.md, ARCHITECTURE.md generation."""

from __future__ import annotations

from dataclasses import dataclass, field

from vaultknox.onboard.analyzer.engine import AnalysisReport
from vaultknox.onboard.config import OnboardConfig
from vaultknox.onboard.documenter.agents_md import generate_agents_md
from vaultknox.onboard.documenter.api_docs import generate_arch_overview
from vaultknox.onboard.documenter.readme_md import generate_readme_md, generate_setup_md


@dataclass(slots=True)
class DocResult:
    filename: str
    path: str
    generated: bool
    overwritten: bool
    skipped: bool = False
    skip_reason: str = ""
    error: str = ""


@dataclass(slots=True)
class DocReport:
    repo_path: str
    results: list[DocResult] = field(default_factory=list)
    generated_count: int = 0
    overwritten_count: int = 0
    skipped_count: int = 0
    error_count: int = 0

    @property
    def all_successful(self) -> bool:
        return self.error_count == 0


class DocGenerator:
    def __init__(self, config: OnboardConfig) -> None:
        self.config = config

    def generate_all(self, report: AnalysisReport) -> DocReport:
        doc_report = DocReport(repo_path=str(self.config.repo_path))

        generators = []
        if self.config.generate_agents_md: generators.append(("AGENTS.md", generate_agents_md))  # noqa: E701
        if self.config.generate_readme_md: generators.append(("README.md", generate_readme_md))  # noqa: E701
        if self.config.generate_setup_md: generators.append(("SETUP.md", generate_setup_md))  # noqa: E701
        if self.config.generate_architecture: generators.append(("ARCHITECTURE.md", generate_arch_overview))  # noqa: E701

        for filename, gen in generators:
            result = self._write_doc(filename, gen(report))
            doc_report.results.append(result)
            if result.generated: doc_report.generated_count += 1  # noqa: E701
            if result.overwritten: doc_report.overwritten_count += 1  # noqa: E701
            if result.skipped: doc_report.skipped_count += 1  # noqa: E701
            if result.error: doc_report.error_count += 1  # noqa: E701

        return doc_report

    def _write_doc(self, filename: str, content: str) -> DocResult:
        output_path = self.config.output_dir / filename
        result = DocResult(filename=filename, path=str(output_path), generated=False, overwritten=False)

        if output_path.exists():
            existing = output_path.read_text(encoding="utf-8")
            if "Auto-generated by VaultKnox Onboard" in existing:
                if not self.config.dry_run:
                    try:
                        output_path.write_text(content, encoding="utf-8")
                        result.generated = True
                        result.overwritten = True
                    except OSError as exc:
                        result.error = str(exc)
                else:
                    result.generated = True
                    result.overwritten = True
            else:
                result.skipped = True
                result.skip_reason = "User-authored file exists; not overwriting"
        else:
            if not self.config.dry_run:
                try:
                    output_path.write_text(content, encoding="utf-8")
                    result.generated = True
                except OSError as exc:
                    result.error = str(exc)
            else:
                result.generated = True
        return result
