"""README.md and SETUP.md generator."""

from __future__ import annotations

from datetime import datetime

from vaultknox.onboard.analyzer.engine import AnalysisReport


def generate_readme_md(report: AnalysisReport) -> str:
    sections: list[str] = []
    sections.append(f"# {report.repo_name}")
    sections.append("")
    sections.append("## Overview")
    sections.append("")
    if report.primary_language:
        lang_text = f"built primarily in {report.primary_language}"
        if report.language_count > 1:
            langs = list(report.languages.keys())
            lang_text += f" with {', '.join(langs[1:4])}"
        sections.append(f"This is a {lang_text} project.")
    sections.append("")
    sections.append("## Getting Started")
    sections.append("")
    sections.append("### Prerequisites")
    sections.append("")
    if report.has_nodejs:
        pkg = report.dependencies.get("nodejs", {})
        sections.append(f"- **Node.js** {pkg.get('engines', {}).get('node', 'latest LTS')}")
        sections.append(f"- **Package manager**: {pkg.get('package_manager', 'npm')}")
    if report.has_python:
        py_info = report.dependencies.get("python", {})
        sections.append(f"- **Python** {py_info.get('requires_python', '>=3.11')}")
    if report.has_rust:
        sections.append("- **Rust** (latest stable)")
    if report.has_go:
        go_info = report.dependencies.get("go", {})
        sections.append(f"- **Go** {go_info.get('go_version', 'latest')}")
    sections.append("")
    sections.append("### Installation")
    sections.append("")
    sections.append("```bash")
    if report.has_nodejs: sections.append("npm install")
    elif report.has_python: sections.append("pip install -e .[dev]")
    elif report.has_rust: sections.append("cargo build")
    elif report.has_go: sections.append("go mod download")
    sections.append("```")
    sections.append("")
    if report.entry_points:
        sections.append(f"Entry point: `{report.entry_points[0]}`")
        sections.append("")
    sections.append("## Project Structure")
    sections.append("")
    for d in report.source_dirs: sections.append(f"- `{d}/` — source code")
    for d in report.test_dirs: sections.append(f"- `{d}/` — tests")
    sections.append("")
    sections.append("## Technology Stack")
    sections.append("")
    for fw in report.frameworks: sections.append(f"- {fw}")
    sections.append("")
    sections.append("---")
    sections.append(f"*Generated by VaultKnox Onboard on {datetime.now().strftime('%Y-%m-%d')}*")
    return "\n".join(sections)


def generate_setup_md(report: AnalysisReport) -> str:
    sections: list[str] = []
    sections.append(f"# {report.repo_name} — Setup Guide")
    sections.append("")
    sections.append(f"*Auto-generated by VaultKnox Onboard on {datetime.now().strftime('%Y-%m-%d')}*")
    sections.append("")
    sections.append("## System Requirements")
    sections.append("- macOS, Linux, or WSL2 (Windows)")
    sections.append("")

    if report.has_nodejs:
        pkg = report.dependencies.get("nodejs", {})
        sections.append(f"1. Install Node.js {pkg.get('engines', {}).get('node', '22')}")
        sections.append("2. Run: `npm install`")
        sections.append("")

    if report.has_python:
        py_info = report.dependencies.get("python", {})
        sections.append(f"1. Install Python {py_info.get('requires_python', '>=3.11')}")
        sections.append("2. Create virtual environment:")
        sections.append("   ```bash")
        sections.append("   python -m venv .venv")
        sections.append("   source .venv/bin/activate")
        sections.append("   ```")
        sections.append("3. Install dependencies:")
        sections.append("   ```bash")
        if report.frameworks.get("uv"): sections.append("   uv sync")
        elif report.frameworks.get("Poetry"): sections.append("   poetry install")
        else: sections.append("   pip install -e .[dev]")
        sections.append("   ```")
        sections.append("")

    if report.has_rust:
        sections.append("1. Install Rust: `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`")
        sections.append("2. Build: `cargo build`")
        sections.append("")

    if report.has_go:
        sections.append("1. Install Go (latest stable)")
        sections.append("2. Run: `go mod download`")
        sections.append("")

    sections.append("## Verify Installation")
    sections.append("")
    sections.append("```bash")
    if report.has_nodejs:
        sections.append("node --version && npm test")
    elif report.has_python:
        sections.append("python --version && python -m pytest")
    elif report.has_rust:
        sections.append("rustc --version && cargo test")
    elif report.has_go:
        sections.append("go version && go test ./...")
    sections.append("```")
    sections.append("")

    return "\n".join(sections)
