"""Skill generation for VaultKnox.

Generates SKILL.md contracts that define how sub-agents should access
credentials from VaultKnox. Keeps agents from freelancing credential discovery.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any

from vaultknox import __version__
from vaultknox.config import expand_runtime_path

# ── Default Skill Template ───────────────────────────────────────────────────────

DEFAULT_SKILL_TEMPLATE = """# SKILL.md — VaultKnox Credential Access

Author: VaultKnox
Version: {version}
Generated: {generated_at}

## Overview

This skill defines the credential access contract for the VaultKnox encrypted vault.
All credential access MUST go through VaultKnox — never hardcode secrets.

## Security Rules

- **NEVER** echo, log, or store credentials in plaintext
- **ALWAYS** use `vaultknox get-masked` or the VaultKnox MCP tool to retrieve credentials
- **NEVER** ask users to paste API keys in chat — redirect to CLI
- **ALWAYS** deliver credentials via secure channels (Signal DM, not chat)
- **ALWAYS** use ephemeral tokens when available

## Credential Access Pattern

For any operation requiring credentials:

1. Check vault via `vaultknox list` or MCP tool `vaultknox_list`
2. Get masked credential via `vaultknox get-masked <id>` or `vaultknox_get_metadata`
3. Use token for environment variable injection (not raw secret)
4. Never store or log the raw credential

Example:
```
# Instead of hardcoding:
openai_api_key = "sk-xxx"

# Use VaultKnox:
result = vaultknox_get_metadata(secret_id="openai-api-key")
# Returns: {id, type, label, token, expires_at}
os.environ["OPENAI_API_KEY"] = result["token"]
```

## Allowed Services

{allowed_services}

## Metadata Only (No Raw Secrets)

These secrets are available via masked view only:

{masked_services}

## Credential Lifecycle

- Secrets expire at `expires_at` — check before use
- Tokens valid for {token_ttl_seconds}s
- Rotated secrets have new IDs — update references after rotation

## Emergency

If a secret is leaked:
1. Report immediately to human operator
2. Use `vaultknox delete <id>` to remove
3. Rotate the credential at the provider
4. Add new credential via `vaultknox add` or `hermes-vault oauth`

---
Generated by VaultKnox. Do not edit manually.
"""


# ── Skill Generator ───────────────────────────────────────────────────────


class SkillGenerator:
    """Generates SKILL.md files from vault policy."""
    
    def __init__(self, path: str | Path | None = None):
        self.paths = expand_runtime_path(path)
        
    def generate(self, agent_id: str | None = None) -> str:
        """Generate SKILL.md content.
        
        Args:
            agent_id: Optional agent ID to scope skills
            
        Returns:
            Generated SKILL.md content
        """
        from vaultknox.config import DEFAULT_TOKEN_TTL_SECONDS
        from vaultknox.vault import VaultKnox
        
        vault = VaultKnox(self.paths)
        secrets = vault.list_secrets() if vault.status().unlocked else []
        
        # Categorize secrets
        allowed = []  # Can get token/env
        masked = []   # Metadata only
        
        for s in secrets:
            sec_type = s.get("type", "")
            label = s.get("label", "")
            sec_id = s.get("id", "")
            
            if sec_type in ("api_key", "oauth"):
                allowed.append(f"- `{sec_id}`: {label}")
            else:
                masked.append(f"- `{sec_id}`: {label}")
        
        # Generate content
        from datetime import datetime
        content = DEFAULT_SKILL_TEMPLATE.format(
            version=__version__,
            generated_at=datetime.now().isoformat(),
            allowed_services="\n".join(allowed) if allowed else "- (none configured)",
            masked_services="\n".join(masked) if masked else "- (none)",
            token_ttl_seconds=DEFAULT_TOKEN_TTL_SECONDS,
        )
        
        return content
    
    def write(self, output_dir: Path, agent_id: str | None = None) -> dict[str, Any]:
        """Generate and write SKILL.md to directory.
        
        Args:
            output_dir: Directory to write SKILL.md
            agent_id: Optional agent ID for naming
            
        Returns:
            Dict with path, hash, services count
        """
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)
        
        content = self.generate(agent_id)
        output_path = output_dir / "SKILL.md"
        output_path.write_text(content)
        
        # Calculate hash for validation
        content_hash = hashlib.sha256(content.encode()).hexdigest()[:16]
        
        from vaultknox.vault import VaultKnox
        vault = VaultKnox(self.paths)
        secret_count = len(vault.list_secrets()) if vault.status().unlocked else 0
        
        return {
            "path": str(output_path),
            "content_hash": content_hash,
            "secret_count": secret_count,
        }
    
    def sync_all(self, skills_dir: Path) -> list[dict[str, Any]]:
        """Sync all skills to skills directory.
        
        Scans ~/.hermes/skills/ for agent directories and generates
        appropriate SKILL.md for each.
        """
        skills_dir = Path(skills_dir)
        if not skills_dir.exists():
            return []
        
        results = []
        for subdir in skills_dir.iterdir():
            if subdir.is_dir() and not subdir.name.startswith("_"):
                result = self.write(subdir)
                result["agent"] = subdir.name
                results.append(result)
        
        return results


# ── CLI Integration ───────────────────────────────────────────────────────


def generate_skill(output_path: Path | None = None, agent_id: str | None = None) -> dict[str, Any]:
    """Generate a SKILL.md file.
    
    Args:
        output_path: Where to write (default: ~/.hermes/skills/vaultknox/SKILL.md)
        agent_id: Optional agent to scope for
        
    Returns:
        Dict with generation result
    """
    if not output_path:
        # Default to ~/.hermes/skills/vaultknox/
        output_path = Path.home() / ".hermes" / "skills" / "vaultknox"
    
    generator = SkillGenerator()
    result = generator.write(output_path, agent_id)
    
    return result


# ── Entry Point ────────────────────────────────────────────────────────────


if __name__ == "__main__":
    result = generate_skill()
    print(json.dumps(result, indent=2))